ALTER TABLE shift_schedules
  ADD COLUMN IF NOT EXISTS is_override BOOLEAN DEFAULT true NOT NULL,
  ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  ALTER COLUMN shift_id DROP NOT NULL;
